name: Build and Check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies and check migrations
        run: |
          pip install -r requirements.txt
          python manage.py makemigrations --check --dry-run

  deploy:
    name: Deploy Application
    needs: build
    if: ${{ success() }}
    runs-on: ubuntu-latest

    steps:
      - name: Print build status
        run: |
          if [ "${{ needs.build.result }}" == "success" ]; then
            echo "✅ Build succeeded"
          else
            echo "❌ Build failed"
            exit 1
          fi
